services:
  node-imua:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imua-node
    ports:
      - "26660:26660"
      - "26656:26656"
    restart: unless-stopped
    volumes:
      - imua_volume:/app/.imuad
      - ./entrypoint.sh:/app/entrypoint.sh

volumes:
  imua_volume:
